version: '2'
services:
  ya-tank:
    image: direvius/yandex-tank
    volumes:
      - ./ssh:/root/.ssh
      - ./test_config:/var/loadtest
    links:
      - lapis
      - lumen
      - slim
      - php
      - openresty
      - openresty_hello
      - openresty_world
      - net_core
      - react
      - react_slim

  lapis:
    build:
      context: ./services/lapis
    volumes:
      - ./ssh:/root/.ssh
    expose:
      - 80
      - 22

  lumen:
    build:
      context: ./services/lumen
    volumes:
      - ./ssh:/root/.ssh
    expose:
      - 80
      - 22

  slim:
    build:
      context: ./services/slim
    volumes:
      - ./ssh:/root/.ssh
    expose:
      - 80
      - 22

  openresty:
    build:
      context: ./services/openresty
    volumes:
      - ./ssh:/root/.ssh
    expose:
      - 80
      - 22

  openresty_hello:
    build:
      context: ./services/openresty_hello
    volumes:
      - ./ssh:/root/.ssh
    expose:
      - 80
      - 22

  openresty_world:
    build:
      context: ./services/openresty_world
    volumes:
      - ./ssh:/root/.ssh
    expose:
      - 80
      - 22

  php:
    build:
      context: ./services/php
    volumes:
      - ./ssh:/root/.ssh
    expose:
      - 80
      - 22

  net_core:
    build:
      context: ./services/net_core
    volumes:
      - ./ssh:/root/.ssh
    expose:
      - 80
      - 22

  react:
    build:
      context: ./services/react
    volumes:
      - ./ssh:/root/.ssh
    expose:
      - 80
      - 22

  react_slim:
    build:
      context: ./services/react_slim
    volumes:
      - ./ssh:/root/.ssh
    expose:
      - 80
      - 22